### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jukisu23** [siara-cc/esp32_arduino_sqlite3_lib#15]
Hello,
I can't find any documentation more than the examples. Is there any?

**Comment by siara-cc** [comment]
The library is a wrapper for the SQLite API whose documentation can be found at `https://sqlite.org/c3ref/funclist.html`.

**Comment by siara-cc** [comment]
See new library https://github.com/siara-cc/sqlite_micro_logger_arduino.
It overcomes all memory problems and corruption issues.
However there are limitations.
For documentation see: https://github.com/siara-cc/sqlite_micro_logger_c.
