### ISSUE TITLE
Arduino Library Manager

### ISSUE THREAD

**Issue by tobozo** [siara-cc/esp32_arduino_sqlite3_lib#3]
hope you don't mind I made the request for you ^_^ 

https://github.com/arduino/Arduino/issues/8541

**Comment by siara-cc** [comment]
Wow.. thanks @tobozo .. I didn't know about it.. I hope many people use it..

**Comment by tobozo** [comment]
looks like it's passed the tests successfully \o/ it should land in the Library Manager in a couple of hours

**Comment by tobozo** [comment]
funny the platformio robot didn't find your project though, I've given it a little help:

```
$ pio lib register https://github.com/siara-cc/esp32_arduino_sqlite3_lib/raw/master/library.properties
The library has been successfully registered and is waiting for moderation
```

**Comment by siara-cc** [comment]
Many thanks @tobozo.. Can I request to add myself or only users can?

**Comment by tobozo** [comment]
I'm not a power user, anyone can request it

**Comment by siara-cc** [comment]
Yes!!  It is on their website.  But they seem to have taken the oldest release though!!  Anyway, the link is there for anyone to upgrade.
![lib_mgr_ss](https://user-images.githubusercontent.com/12986780/53634254-b9d71e80-3c3f-11e9-824a-ed3afb93584b.png)

**Comment by tobozo** [comment]
that's another registry, platformio registry is that one: https://platformio.org/lib/search?query=sqlite3

actually I don't even know if this library works on platformio, but it's only a matter of adding a plaformio.ini with the correct -D flags  (and the corresponding #ifdef's in the code)

**Comment by siara-cc** [comment]
yes, I have heard about PIO.. I haven't used it either..

**Comment by tobozo** [comment]
well I just tried to import it via `pio lib install https://github.com/siara-cc/esp32_arduino_sqlite3_lib.git` and it compiled the spiffs example just fine

**Comment by tobozo** [comment]
congrats !!!

![image](https://user-images.githubusercontent.com/1893754/53635144-7dde9200-3c1c-11e9-95ed-8da16a84507d.png)

**Comment by tobozo** [comment]
this will only make your *releases* available from the Library Manager, totally different from doing a git clone from the master

**Comment by siara-cc** [comment]
right.. GUI Frontend that will cover non-CLI users too.

**Comment by tobozo** [comment]
Actually the current release does not compile on Arduino IDE (I had to overwrite the library folder with the current master source) so you may want to increment your version in library.properties, then create a tag and produce a release.

Platformio and Arduino library managers will automatically detect this release and send and add it to the versions list (no need to re-submit) as long as the library.properties version and release values match, and the version increments.

**Comment by tobozo** [comment]
And platformio coped with the new version https://platformio.org/lib/show/6173/Sqlite3Esp32 \o/

**Comment by siara-cc** [comment]
Excellent.. I also requested to add my other libraries on both platforms.. Thanks @tobozo ...
