### ISSUE TITLE
get error on index

### ISSUE THREAD

**Issue by Rita-GE** [siara-cc/esp32_arduino_sqlite3_lib#30]
Hello @siara-cc ，
I would get the "disk I/O error" error when running SQLite database on SPIFFS.

I have tried creating an INDEX, but failed.

Here are the messages:

- SELECT * FROM test1 WHERE id = 1
- Callback function called: id = 1
- content = Hello, World from test1
- 
- Operation done successfully
- Time taken:7318
- CREATE INDEX testIdx ON test1(id ASC);
- SQL error: disk I/O error
- Time taken:342706

And my code:
`db_open("/spiffs/test1.db", &db1)
db_exec(db1, "CREATE TABLE test1 (id INTEGER, content);")
db_exec(db1, "INSERT INTO test1 VALUES (1, 'Hello, World from test1')")
db_exec(db1, "CREATE INDEX testIdx ON test1(id ASC);");
sqlite3_close(db1);`

Can you give me any lead?
Thank you.

**Comment by siara-cc** [comment]
Please try the solution that was kindly shared by another user: https://github.com/siara-cc/esp32_arduino_sqlite3_lib/issues/28#issuecomment-646920628.
This opens SPIFFS with max 5 simultaneous open files, which might solve the problem.  Please try increasing it if it does not work too.

I believe this parameter is also possible with SPIFFS.open().
