### ISSUE TITLE
implementing JSON as reference in callback function

### ISSUE THREAD

**Issue by kiwi85** [siara-cc/esp32_arduino_sqlite3_lib#31]
First of all thank you for making it possible to work with sqlite on a esp32 chip!
As I am working with JSON v6 to get process data from database further I now want to save the requested data within the callback function into a JSON Object and pass that back to the main function.
The library offers a void*data parameter pointer that can be used to pass anything to the callback function.
I am completely new to pointers and would kindly ask your help.
here is my code so far:
`
static int callback(void *data, int argc, char **argv, char **azColName) {
//I need to use *data for filling a JSON Object-->but how???
   int i;
   for (i = 0; i<argc; i++){
       Serial.printf("%s = %s\n", azColName[i], argv[i] ? argv[i] : "NULL");
   }
   Serial.printf("\n");
   return 0;
}

int db_open(const char *filename, sqlite3 **db) {
   int rc = sqlite3_open(filename, db);
   if (rc) {
       Serial.printf("Can't open database: %s\n", sqlite3_errmsg(*db));
       return rc;
   } else {
       Serial.printf("Opened database successfully\n");
   }
   return rc;
}

char *zErrMsg = 0;
int db_exec(sqlite3 *db, const char *sql) {
  DynamicJsonDocument doc(1024);
  JsonObject data=doc.createNestedObject();
   Serial.println(sql);
   long start = micros();
   int rc = sqlite3_exec(db, sql, callback, &data, &zErrMsg);//JSON Object needs to be passed to callbackfunctino but how???
   if (rc != SQLITE_OK) {
       Serial.printf("SQL error: %s\n", zErrMsg);
       sqlite3_free(zErrMsg);
   } else {
       Serial.printf("Operation done successfully\n");
       serializeJson(data,Serial);
       free(data);
   }
   Serial.print(F("Time taken:"));
   Serial.println(micros()-start);
   return rc;
}
`
please give me any hint on how to make use of json within callback and pass those values back.
I simply want to use one jsonobject which is created once a enquery accours. Then filled with data within the callback and the content then send to a client after no more rows are available.
chears,
Julian

**Comment by siara-cc** [comment]
Check out https://arduinojson.org/
You can load the strings stored in columns pass to call back function (argv[i]) as input to this library and change.
For storing, you will have to issue UPDATE sql statements after converting the modified Json back to string.
