### ISSUE TITLE
Can i host a webpage from spiffs if i use sqlite3_lib?

### ISSUE THREAD

**Issue by zekageri** [siara-cc/esp32_arduino_sqlite3_lib#32]
I'am wondering if it is possible to host a webpage from flash if i use this sql lib.
For example if i use async http requests like this:

```
server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    AsyncWebServerResponse* response = request->beginResponse(LITTLEFS, "/Home_index.html", "text/html");
    response->addHeader("Content-Encoding", "gzip");
    request->send(response);
});
```

Will it work if i init the sqlite3?

**Comment by siara-cc** [comment]
This library works with requests from WiFi. But I don't understand your question. You want to serve static pages stored in SQLite database?

**Comment by zekageri** [comment]
Yes kindof. Or just make part of the flash to sqlite.
