### ISSUE TITLE
How to get searched fields contents?

### ISSUE THREAD

**Issue by williamesp2015** [siara-cc/esp32_arduino_sqlite3_lib#5]
sqlite3_initialize();
   if (openDb("/sd/DATA1.db", &db1))
   {
How to make query without using    rc = db_exec(db1, "Select * from FIELD? where name = '???'"); to be able to access selected records contents
     sqlite3_close(db1);
   }

**Comment by siara-cc** [comment]
For using select sql statement, db_exec() or db_prepare_v2() has to be used.  If you need example for db_prepare_v2(), please see `sqlite3_webquery` example.
