### ISSUE TITLE
SD Card mount failure

### ISSUE THREAD

**Issue by bcookew** [siara-cc/esp32_arduino_sqlite3_lib#63]
Hiya, I have been trying to get your SQLite console demo code running most of today. I have an SD Card reader that I can mount and use without your code(confirming it works) but if I try with your code the card fails to mount. Have you come across this before?

**Comment by siara-cc** [comment]
Hi, no what is the error you are facing?

**Comment by bcookew** [comment]
Still learning C++ and Arduino. I made a bunch of rookie errors. All cleared up now. Thanks for the great library.
