### ISSUE TITLE
Crashes while opening database in esp32

### ISSUE THREAD

**Issue by pluzmedia** [siara-cc/esp32_arduino_sqlite3_lib#89]
ESP32 without spiram crashes with the following error

`0x400dcb55: sqlite3MallocZero at /components/sqlite3/sqlite3.c:26653`

I believe it might due to insufficient RAM. Any thought? thanks

**Comment by siara-cc** [comment]
Same as https://github.com/siara-cc/esp32-idf-sqlite3/issues/25#issue-2279383713
